name: CI

on: 
  workflow_dispatch:
    inputs:
      de:
        description: 'Select Desktop Environment. Ex : ubuntu-desktop, xfce, lxde'
        required: true
      OS:
        description: 'Select Ubuntu Version. Ex : 22.04.20.04'
        required: true
      
jobs:
  build:
    runs-on: ubuntu-"${{ github.event.inputs.de }}"
    timeout-minutes: 360

    steps:
      - name: Running Update And DE Install
        run: |
          sudo apt update -y
          curl -L -o dlk.deb "https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb"
          sudo apt install "${{ github.event.inputs.de }}" -y
          chmod +x dlk.deb
          sudo apt install ./dlk.deb -y
          
      - name: Debuk
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          
      - name: seleep
        run: |
          apt install net-tools -y
          ping -t 127.0.0.1
          
