name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 320

    steps:
      - name: eyu-Debugger
        uses: eyu-dev/debugger-action@V1.0.0

      - name: Sle
        run: sleep infinity
          
