name: CI

on: 
  workflow_dispatch:
    inputs:
      de:
        description: 'Select Desktop Environment. Ex : ubuntu-desktop, xfce, lxde'
        required: true
      
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Running Update And DE Install
        run: |
          sudo apt update -y
          sudo apt install "${{ github.event.inputs.de }}" -y

      - name: Debuk
        uses: eyu-dev/debugger-action@V1.0.0

      - name: seleep
        run: sleep infinity
          
