name: Ngrok - Docker

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: 'ngrok auth token'
        required: true
      link_iso:
        description: 'dán link iso của ae vô đây'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-2004
    steps:
      - name: Menjalankan actions/checkout@v2
        uses: actions/checkout@v2
        
      - name: Menjalankan Update Dan Menginstall Docker
        run: |
          sudo apt update -y
          sudo apt install wget curl cpulimit -y
          sudo apt install docker-compose -y
          curl -L -o ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -zxvf ngrok.tgz
          ./ngrok config add-authtoken "${{ github.event.inputs.ngrok }}"
      - name: Menjalankan Qemu Melalui Docker Compose
        run: |
          sudo chmod 666 /dev/kvm
          sudo mkdir /isos/
          sudo curl -L -o /isos/a.iso "${{ github.event.inputs.link_iso }}" 
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo curl -L -o /isos/driver.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win-0.1.240.iso
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          echo "Peluncuran Berhasil, Sekarang Buka Dashboard Ngrok dan Klik Link Yang Ada Di Endpoints"
          ./ngrok http 8006 --region ap &>/dev/null &
          sudo docker-compose up 
      
